### ISSUE TITLE
[MEMO] Bidi support for blockquotes

### ISSUE THREAD

**Issue by iMrDJAi** [iMrDJAi/bidimarkdown-spec#1]
[Blockquotes](https://spec.commonmark.org/0.30/#block-quotes) are exceptional, we need to precisely define how they should behave with bidirectional text.

Usually, developers add some CSS to give blockquotes that border on the left. However, in the case of right to left text, the border should be on the right instead, following the beginning of the sentence. There is a pure CSS solution that makes the border follow direction of elements: `border-inline-start`!

Blockquote elements aren't direct parents to the text inside. Instead, there are nested paragraph elements that contain the text:

Markdown:
```md
> text
```

HTML:
```html
<blockquote>
  <p>text</p>
</blockquote>
```

Giving the `dir="auto"` attribute to both `<blockquote>` and `<p>` elements prevents the `border-inline-start` trick from working because it will apply the `unicode-bidi: isolate;` CSS rule to `<p>` elements, which will essentially isolate the text direction from the `<blockquote>` elements that rely on the direction of the first strong character to determine their own direction.

Also, the goal is when you quote existing bidirectional content, the directions should remain the same. In other words, appearance of text within a blockquote should be as close as possible to the same text unquoted. Thus, blockquote elements may have nested blockquotes or paragraphs or any other block elements taking their opposite direction.

**Solution:** Add `dir="auto"` to all block elements except first child of another block element!

![image](https://user-images.githubusercontent.com/42304709/151843810-9eb8e27b-361b-4f57-aa8e-c55a429ab45d.png)

Markdown:
```md
> عربية1 عربية2 English عربية3 عربية4
>
> > عربية1 عربية2 English عربية3 عربية4 
>
> > English1 English2 عربية English3 English4
>
> English1 English2 عربية English3 English4
```

HTML:
```html
<blockquote dir="auto">
  <p>عربية1 عربية2 English عربية3 عربية4</p>
  <blockquote dir="auto">
    <p>عربية1 عربية2 English عربية3 عربية4</p>
  </blockquote>
  <blockquote dir="auto">
    <p>English1 English2 عربية English3 English4</p>
  </blockquote>
  <p dir="auto">English1 English2 عربية English3 English4</p>
</blockquote>
```

**Comment by ahangarha** [comment]
Hi @iMrDJAi

I have given thought to this, and I am very convinced that your proposal for not adding `dir="auto"` is good. I agree with it.
