### ISSUE TITLE
[MEMO] Bidi support for lists

### ISSUE THREAD

**Issue by iMrDJAi** [iMrDJAi/bidimarkdown-spec#2]
[Lists](https://spec.commonmark.org/0.30/#lists) (\<ol>, \<ul>) are [container block elements](https://spec.commonmark.org/0.30/#container-blocks), they contain [list items](https://spec.commonmark.org/0.30/#list-items) (\<li>). List items contain text. However, they are also container block elements that may contain other block elements such as nested lists.

Lists should always take a single direction, which means if the direction of the first list item is right to left, the other list items should all have a right to left direction (and the opposite is true). Otherwise, they will look ugly, messy, and will be hard to read.

Adding `dir="auto"` to all block elements doesn't work well with lists. See this example:

Markdown:

```md
RTL:

- تجربة
- test

1. تجربة
2. test

LTR:

- test
- تجربة

1. test
2. تجربة
```

Result:

![image](https://user-images.githubusercontent.com/42304709/159015339-7d36e355-f3c5-49a8-8e3e-aa9ccc0a2bd4.png)

```html
<p dir="auto">RTL:</p>
<ul dir="auto">
  <li dir="auto">تجربة</li>
  <li dir="auto">test</li>
</ul>
<ol dir="auto">
  <li dir="auto">تجربة</li>
  <li dir="auto">test</li>
</ol>
<p dir="auto">LTR:</p>
<ul dir="auto">
  <li dir="auto">test</li>
  <li dir="auto">تجربة</li>
</ul>
<ol dir="auto">
  <li dir="auto">test</li>
  <li dir="auto">تجربة</li>
</ol>
```

Notice how the list markers are completely broken. To fix that, we should remove the `dir` attribute from list items:

![image](https://user-images.githubusercontent.com/42304709/159015975-04cb91eb-8cac-4782-9fce-3928794f1034.png)

```html
<p dir="auto">RTL:</p>
<ul dir="auto">
  <li>تجربة</li>
  <li>test</li>
</ul>
<ol dir="auto">
  <li>تجربة</li>
  <li>test</li>
</ol>
<p dir="auto">LTR:</p>
<ul dir="auto">
  <li>test</li>
  <li>تجربة</li>
</ul>
<ol dir="auto">
  <li>test</li>
  <li>تجربة</li>
</ol>
```

Another issue with nested lists:

Markdown:

```md
RTL:

- تجربة
- - test
- - - test
- - - تجربة

LTR:

- test
- - تجربة
- - - تجربة
- - - test
```

![image](https://user-images.githubusercontent.com/42304709/159020560-6730c314-6135-46d2-8385-b697ca542ba4.png)

```html
<p dir="auto">RTL:</p>
<ul dir="auto">
  <li>تجربة</li>
  <li>
    <ul dir="auto">
      <li>test</li>
    </ul>
  </li>
  <li>
    <ul dir="auto">
      <li>
        <ul dir="auto">
          <li>test</li>
        </ul>
      </li>
    </ul>
  </li>
  <li>
    <ul dir="auto">
      <li>
        <ul dir="auto">
          <li>تجربة</li>
        </ul>
      </li>
    </ul>
  </li>
</ul>
<p dir="auto">LTR:</p>
<ul dir="auto">
  <li>test</li>
  <li>
    <ul dir="auto">
      <li>تجربة</li>
    </ul>
  </li>
  <li>
    <ul dir="auto">
      <li>
        <ul dir="auto">
          <li>تجربة</li>
        </ul>
      </li>
    </ul>
  </li>
  <li>
    <ul dir="auto">
      <li>
        <ul dir="auto">
          <li>test</li>
        </ul>
      </li>
    </ul>
  </li>
</ul>
```

Some list markers are aligned on the opposite side. This is a total mess! We can fix that by removing the `dir` attribute from nested lists:

![image](https://user-images.githubusercontent.com/42304709/159024048-42efffb1-8c03-4eb8-aa13-bdb599785944.png)

```html
<p dir="auto">RTL:</p>
<ul dir="auto">
  <li>تجربة</li>
  <li>
    <ul>
      <li>test</li>
    </ul>
  </li>
  <li>
    <ul>
      <li>
        <ul>
          <li>test</li>
        </ul>
      </li>
    </ul>
  </li>
  <li>
    <ul>
      <li>
        <ul>
          <li>تجربة</li>
        </ul>
      </li>
    </ul>
  </li>
</ul>
<p dir="auto">LTR:</p>
<ul dir="auto">
  <li>test</li>
  <li>
    <ul>
      <li>تجربة</li>
    </ul>
  </li>
  <li>
    <ul>
      <li>
        <ul>
          <li>تجربة</li>
        </ul>
      </li>
    </ul>
  </li>
  <li>
    <ul>
      <li>
        <ul>
          <li>test</li>
        </ul>
      </li>
    </ul>
  </li>
</ul>
```

**Conclusion:** We should not give `dir="auto"` to any child block-elements of lists. Only top-level lists should have the `dir` attribute set to `auto`.

**Comment by ahangarha** [comment]
I agree 👍🏾
