### ISSUE TITLE
[MEMO] Bidi support for code blocks

### ISSUE THREAD

**Issue by iMrDJAi** [iMrDJAi/bidimarkdown-spec#4]
Code blocks are consisted of block `<pre>` elements wrapping inline `<code>` elements. `<pre>` elements provide a way to embed raw text content while preserving all white-space characters (eg. space, new line).

Bidi support for code blocks is straight forward, adding `dir="auto"` to `<pre>` elements will do the trick:

![image](https://github.com/iMrDJAi/bidimarkdown-spec/assets/42304709/96708d38-a0ee-4953-9c35-dcb5383e7ea1)

Markdown:

~~~md
```
عربية1 عربية2 English عربية3 عربية4
English1 English2 عربية English3 English4
عربية1 عربية2 English عربية3 عربية4
English1 English2 عربية English3 English4
```
~~~

HTML:
```html
<pre dir="auto"><code>عربية1 عربية2 English عربية3 عربية4
English1 English2 عربية English3 English4
عربية1 عربية2 English عربية3 عربية4
English1 English2 عربية English3 English4
</code></pre>
```

Some implementations might choose to force text alignment to the left with CSS:

![image](https://github.com/iMrDJAi/bidimarkdown-spec/assets/42304709/2341bd8d-106e-4406-a2e9-8f371df304ef)

While it's not mandatory, it's better to avoid this and keep the alignment automatic.

**Comment by iMrDJAi** [comment]
@ahangarha Please review this

**Comment by ahangarha** [comment]
I think this follows the general rule for nested elements: all child elements except the first one should get `dir="auto"`. Setting direction style would be the decision to be made by the programmer for the use case (as mentioned). I prefer to keep it auto.
