### ISSUE TITLE
[MEMO] Bidi support for tables

### ISSUE THREAD

**Issue by iMrDJAi** [iMrDJAi/bidimarkdown-spec#5]
Supporting bidi in [tables](https://github.github.com/gfm/#tables-extension-) is:

1. Displaying bidirectional text within each cell in the correct order.
2. Mirroring tables depending on the direction of the text within the first cell (first strong character).
3. Aligning tables to the direction of the text within the first cell (**optional**).

And to accomplish that we need to:

1. Add `dir="auto"` to `<table>` (**point 2**).
2. Add `dir="auto"` to each table cell (`<th>`, `<td>`), excluding the first `<th>`, which its direction should not be isolated from `<table>` (**point 1**).
3. Optionally apply `display: block;` to `<table>` with **CSS**, since elements with `display: table;` won't be aligned to the right when having RTL direction (**point 3**). 

Before (table aligned to the left, order of words is broken):

![image](https://github.com/iMrDJAi/bidimarkdown-spec/assets/42304709/a88927e8-f29b-4443-93b9-f409277278be)

After (table mirrored, aligned to the right, since the first word is RTL, order of words is correct):

![image](https://github.com/iMrDJAi/bidimarkdown-spec/assets/42304709/d2ebfee1-3561-420d-90cf-a0a49165b3cf)

Markdown:

```md
| عربية1 Eng عربية2 | Eng1 عربية Eng2 |
|--|--|
| Eng1 عربية Eng2 | عربية1 Eng عربية2 |
```

HTML:

```html
<table dir="auto">
  <thead>
    <tr>
      <th>عربية1 Eng عربية2</th>
      <th dir="auto">Eng1 عربية Eng2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td dir="auto">Eng1 عربية Eng2</td>
      <td dir="auto">عربية1 Eng عربية2</td>
    </tr>
  </tbody>
</table>
```

Interesting that the text alignment in cells can be explicitly set by adding colons (`:`) to [delimiter rows](https://github.github.com/gfm/#delimiter-row), which provides more flexibility.

**Comment by iMrDJAi** [comment]
@ahangarha

**Comment by ahangarha** [comment]
Looks good. Agree. 
And this follows the same general rule: Do not apply `dir="auto"` to the immediate child.
