### ISSUE TITLE
[MEMO] General rule for bidi support

### ISSUE THREAD

**Issue by iMrDJAi** [iMrDJAi/bidimarkdown-spec#6]
**Introduction:** Bidirectional content is content that has characters in mixed directions, both LTR and RTL. Supporting bidirectional content is:

- Displaying bidirectional text in the correct order (**priority 1**).
- Mirroring/flipping HTML layouts depending on the contained text direction (**priority 2**).
- Aligning HTML elements and layouts to the direction of their contained text (**priority 3**).

**Problem:** The problem with bidirectional content is that it appears broken in most implementations. For example, in the case of RTL text, the order of words would completely flip by just inserting a single LTR character within. Here is a demonstration (from google.com):

Right to left text:

![image](https://github.com/iMrDJAi/bidimarkdown-spec/assets/42304709/4724a0ea-9c08-4c5a-bd6b-e9be20062283)

Mixed text (broken):

![image](https://github.com/iMrDJAi/bidimarkdown-spec/assets/42304709/a858101f-9ab2-4c29-90d0-90250e0c0623)

Mixed text (Corrected):

![image](https://github.com/iMrDJAi/bidimarkdown-spec/assets/42304709/e8215e5f-adf1-4384-80d9-3e36c4589c69)

**Solution:** After deep research we have concluded a general rule for supporting bidirectional content that works with (almost) every case:

1. Adding the `dir="auto"` [attribute](https://www.w3schools.com/tags/att_global_dir.asp) to HTML container block elements:
    - By container block elements we mean HTML elements that are considered [block-level](https://www.w3schools.com/html/html_blocks.asp) (starting on a new line and taking 100% of the available width) and may contain any other content such as text or other elements. For example [\<p>](https://www.w3schools.com/tags/tag_p.asp), [\<table>](https://www.w3schools.com/tags/tag_table.asp) and [\<video>](https://www.w3schools.com/tags/tag_video.asp) are container block elements. However, [\<hr>](https://www.w3schools.com/tags/tag_hr.asp) or inline elements like [\<a>](https://www.w3schools.com/tags/tag_a.asp) are not.
    - Adding `dir="auto"` will ensure that any contained bidirectional text is rendered in the correct order by applying the correct [Unicode Bidirectional Algorithm](https://www.w3.org/International/articles/inline-bidi-markup/uba-basics) with [CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/unicode-bidi).
    - Example:

      **Markdown:**
      ```md
      # Heading
      ---
      **Paragraph**
      ```
      **HTML:**
      ```html
      <h1 dir="auto">Heading</h1>
      <hr>
      <p dir="auto">
          <strong>Paragraph</strong>
      </p>
      ```
2. There are exceptions where container block elements must not have the `dir="auto"` attribute:
    - If we have a linked list of HTML container block elements starting at root, where each node is the direct first child of the previous one, we must only give `dir="auto"` to the root node. Otherwise, the root node will be isolated from text that determines its direction. By root nodes we mean nodes with a depth of 0, or non-first child nodes.
    - Example:

      **Markdown:**
        ```md
        > > > Quoted paragraph
        >
        > > فقرة مقتبسة
        ```
        **HTML:**
        ```html
        <blockquote dir="auto">
            <blockquote>
                <blockquote>
                    <p>Quoted paragraph</p>
                </blockquote>
            </blockquote>
            <blockquote dir="auto">
                <p>فقرة مقتبسة</p>
            </blockquote>
        </blockquote>
         ```
    - We must not add `dir="auto"` to an element if that would cause the layout to break, or UI/UX issues. For example, list items are exempt from having the attribute due to an issue with list markers. Each exception of this sort is documented separately.
    - Example:

      **Markdown:**
        ```md
        - test
        - تجربة
        ```
        **HTML:**
        ```html
        <ul dir="auto">
            <li>test</li>
            <li>تجربة</li>
        </ul>
         ```

**Comment by iMrDJAi** [comment]
@ahangarha Have a look.

**Comment by ahangarha** [comment]
Looks good.
I think it can be written in a simpler language. Also I think it should be independent from Markdown. It should be the responsibility of the parsers (markdown, bbcode,...) to return the right formatted HTML as it is described by these rules.

**Comment by iMrDJAi** [comment]
> I think it can be written in a simpler language.

@ahangarha I understand. Been struggling to find simpler terms without losing the meaning, it was harder than I thought. Just acknowledge me of which points you want me to simplify.

> I think it should be independent from Markdown

Yeah, the only reason why I have included examples in Markdown is that this repo is Markdown related. The rules here apply for HTML.

By any chance, can you please review the rules themselves and test them with real life examples later?

**Comment by ahangarha** [comment]
I think the most important thing is that we have reached to a set of simple rules. Rest is just writing, and rewriting,...

The only thing I haven't tested yet is tables. I think my implementation would be different slightly but we will see it by the end of this week. I am rewriting https://github.com/dobidi/bidify-rb to be more flexible. Then I can test tables with the current rules. I expect it to work fine.

**Comment by iMrDJAi** [comment]
@ahangarha Great! Been working on markdown-it-bidi on my side, the results were incredible. I'll keep you updated!
